name: Deploy to cPanel

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cPanel git pull + .cpanel.yml deployment
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: ${{ secrets.CPANEL_HOSTNAME }}
          cpanel_username: ${{ secrets.CPANEL_USERNAME }}
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          repository_root: ${{ secrets.CPANEL_REPO_ROOT }}
          branch: main
